# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/bond_logo.png"
    keywords: bond cryptocurrency jamesbond memecoin bitcoin
    backgroundpic : "img/bond_logo_dark.png"

Intro:
    name: Bond
    slogan: "My name is Bond... James Bond, The one meme coin to rule them all ğŸ”« ğŸï¸ ğŸ‘¯â€â™€ï¸ <br/> Launching soon on Solana "
    HeadButton: BOND

Nav:
    Home_name: Home
#    is_use_categories : true
#    categories_name: åˆ†ç±»
#    is_use_archives : false
#    archives_name: å½’æ¡£
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
#        github: https://github.com/miccall
#        500px: http://500px.com
        twitter: https://x.com/jamesbonddog
        telegram: https://t.me.jamesbonddog
        
    pages:
        About:
            link: "/about/"
#        å›¢é˜Ÿ :
#            link: "/group/"
#        å›¾åº“ :
#            link: "/gallery/"
#        æ ‡ç­¾:
#            link: "/tag/"
#        #è‡ªå®šä¹‰æ ‡ç­¾å
#        #   linkï¼šâ€œè·¯å¾„â€

MainFirst:
    name: Beware Meme Mafia
    pic_url: /img/mafia.png
    goto_ulr: ""

#Gallery :
#    title: Mr.metro
#    description: Just another fine responsive

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System è‡ªå®šä¹‰ä»£ç æ¸²æŸ“ 
# default dark funky okaidia twilight coy solarized  å¯é€‰é¡¹  
# link to review : http://prismjs.com/index.html   å®˜ç½‘é¢„è§ˆ
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus_click
    shortname: http-miccall-tech
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # ä½¿ç”¨ valine è¯·å…ˆæ‰§è¡Œ npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'your appId'
       appKey: 'your appkey'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive


# Leancloud Views
leancloud:
    enable: false
    app_id: #ä½ çš„ app_id
    app_key: #ä½ çš„ app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi ä¸è’œå­ Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax æ”¯æŒåº“
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
